### ISSUE TITLE
btbcm.ko is missing

### ISSUE THREAD

**Issue by xueliu** [namezis/openwrt-stm32mp#1]
Hello,

At first thanks a lot for your great work !

But I am facing a problem when compiling the firmware. I use your default `config_stm32mp1_dk2`
but update the kernel version from `v4.19-stm32mp-r2` to `v4.19-stm32mp-r2`.
I am not expert of bluetooth module.  So could you please help me out ? Thanks.

```
SHELL= flock /home/lx/workspace/openwrt-stm32mp1/tmp/.root-copy.flock -c 'cp -fpR /home/lx/workspace/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/packages/.pkgdir/kernel/. /home/lx/workspace/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-stm32mp1/'
touch /home/lx/workspace/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-stm32mp1/stamp/.kernel_installed
ERROR: module '/home/lx/workspace/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-4.19.49-stm32mp/drivers/bluetooth/btbcm.ko' is missing.
modules/other.mk:145: recipe for target '/home/lx/workspace/openwrt-stm32mp1/bin/targets/stm32mp1/generic/packages/kmod-bluetooth_4.19.49-stm32mp-1_arm_cortex-a7_neon-vfpv4.ipk' failed
make[3]: *** [/home/lx/workspace/openwrt-stm32mp1/bin/targets/stm32mp1/generic/packages/kmod-bluetooth_4.19.49-stm32mp-1_arm_cortex-a7_neon-vfpv4.ipk] Error 1
make[3]: Leaving directory '/home/lx/workspace/openwrt-stm32mp1/package/kernel/linux'
time: package/kernel/linux/compile#3.58#0.34#3.91
package/Makefile:111: recipe for target 'package/kernel/linux/compile' failed
make[2]: *** [package/kernel/linux/compile] Error 2
make[2]: Leaving directory '/home/lx/workspace/openwrt-stm32mp1'
package/Makefile:107: recipe for target '/home/lx/workspace/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/lx/workspace/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lx/workspace/openwrt-stm32mp1'
/home/lx/workspace/openwrt-stm32mp1/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2
```

**Comment by namezis** [comment]
Hello Xueliu,

Thanks for the message. I did not think any one would use it.

I will have a look what is going on with the Broadcom Bluetooth module. I had to hack it a bit to allow module/firmware load base on configuration.

As well I assume you want tag v4.19-stm32mp-r2.5

Available STM32 tags are:

v4.19-stm32mp-r1
v4.19-stm32mp-r1.2
v4.19-stm32mp-r1.3
v4.19-stm32mp-r1.4
v4.19-stm32mp-r1.5
v4.19-stm32mp-r2
v4.19-stm32mp-r2.1
v4.19-stm32mp-r2.2
v4.19-stm32mp-r2.3
v4.19-stm32mp-r2.4
v4.19-stm32mp-r2.5

Best regards
Tomasz Zeman

**Comment by namezis** [comment]
Ok, I fixed the compilation.

Looks like the new kernel does not default CONFIG values to Y, when one is not provided. Generally the Bluetooth infrastructure is not very well maintained in OpenWRT. The master branch is still like that:

![image](https://user-images.githubusercontent.com/1754783/73351443-15dc7400-42e3-11ea-9533-2d1653a05aba.png)

Hopefully it will work for you.

Best regards
Tomasz Zeman

**Comment by xueliu** [comment]
Thanks. It is working.

**Comment by tudejun** [comment]
Hi, I met the issue recently, would you let me know how to modify the file so openwrt can compile successfully?

**Comment by namezis** [comment]
tudejun you wrote:

> Hi, I met the issue recently, would you let me know how to modify the file so openwrt can compile successfully?

Would you be able to create a new issue and describe what your problem is?

Add as many details as possible, and I see if I can help you.
