### ISSUE TITLE
How to flash the sdcard.bin

### ISSUE THREAD

**Issue by krispstack** [namezis/openwrt-stm32mp#2]
HI 
How to flash the openwrt-stm32mp1-dk2-basic-ext4-sdcard.bin?

Thanks

**Comment by namezis** [comment]
Hmm, which ever way you feel comfortable with.

e.g. using dd:

$ sudo dd if=./openwrt-stm32mp1-dk2-basic-ext4-sdcard.bin of=/dev/mmcblk0 bs=8M conv=fdatasync status=progress

Some reference is here: https://wiki.st.com/stm32mpu/wiki/How_to_populate_the_SD_card_with_dd_command

**Comment by krispstack** [comment]
Hi @namezis 
thanks for the quick reply
Tried the same, but board is not booting,

http://www.myirtech.com/list.asp?id=623 - This is the board am using

Thanks

**Comment by namezis** [comment]
Yea,

This OpenWRT was only for STM32MP157C MPU: https://www.st.com/en/evaluation-tools/stm32mp157c-dk2.html

Your module MYD-YA157C Development Board, has some additional storage. 
There are some jumpers on the basebaord under the WIFI module. Try fiddle with them.

If that does not help flash the vendor u-boot and see if it shows up on hardware console.

**Comment by krispstack** [comment]
HI @namezis 

Yes the board has 4GB eMMC and SD card options to Boot. I have selected SD option with the openwrt image. But the board is not booting UP. WIFI I can make it work later once if I boot Openwrt successfully.


The board is booting with default firmware which is supplied by vendor. Now I am trying to boot the board with openwrt

Thanks
KarthiG

**Comment by namezis** [comment]
As with every baseboard there are some customisation.

You should have a look at the changes here:

https://github.com/MYiR-Dev/myir-st-u-boot/commits/develop

I assume that the whole ST manifest is here: https://github.com/MYiR-Dev/myir-st-manifest

From the above manifest the kernel is here: https://github.com/MYiR-Dev/myir-st-linux/commits/develop

**Comment by namezis** [comment]
The kernel and other sources are under: http://d.myirtech.com/MYD-YA157C/
