### ISSUE TITLE
i port to dk2 but i dont know how to make config-5.4

### ISSUE THREAD

**Issue by LazyCat-xiao** [namezis/openwrt-stm32mp#3]
i make but it not work

**Comment by LazyCat-xiao** [comment]
not your repo. is my repo.

**Comment by namezis** [comment]
There are 6 base fragments added over ARM architecture defualts:

fragment-01-multiv7_cleanup.config
fragment-02-multiv7_addons.config
fragment-03-systemd.config
fragment-04-optee.config
fragment-05-modules.config
fragment-06-signature.config

You can build the STM32MP1 default config with e.g.: 

$ make ARCH=arm defconfig fragment-01-multiv7_cleanup.config fragment-02-multiv7_addons.config fragment-03-systemd.config fragment-04-optee.config fragment-05-modules.config fragment-06-signature.config 

plus whatever you need e.g.: fragment-90-lazycat-modules.config

**NOTE:** Only fragments 01 and 02 are with the kernel the rest you need to copy to arch/arm/configs before invoking the above command.

**Comment by LazyCat-xiao** [comment]
i use your repo and it worry.
logs: make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/lazy/openwrt-stm32mp1/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 1
i think your config-5.4 have some problem

**Comment by namezis** [comment]
Can you bring the error on top and paste it here?

**Comment by LazyCat-xiao** [comment]
sorry ，i worry 。 but i dont know i build and it will  report undefined reference to `pthread_once'

**Comment by LazyCat-xiao** [comment]
logs:
make[5]: Entering directory '/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119'
  HOSTCC  scripts/extract-cert
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-eng_all.o): In function `ENGINE_load_builtin_engines':
eng_all.c:(.text+0x30): undefined reference to `pthread_once'
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-err.o): In function `ERR_load_ERR_strings':
err.c:(.text+0xb4e): undefined reference to `pthread_once'
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-err_all.o): In function `ERR_load_crypto_strings':
err_all.c:(.text+0xaf): undefined reference to `pthread_once'
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): In function `OpenSSL_add_all_ciphers':
c_all.c:(.text+0x9df): undefined reference to `pthread_once'
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): In function `OpenSSL_add_all_digests':
c_all.c:(.text+0x9ff): undefined reference to `pthread_once'
/home/lazy/openwrt-stm32mp1/staging_dir/host/lib/libcrypto.a(libcrypto_la-crypto_init.o):crypto_init.c:(.text+0x51): more undefined references to `pthread_once' follow
collect2: error: ld returned 1 exit status
scripts/Makefile.host:107: recipe for target 'scripts/extract-cert' failed
make[6]: *** [scripts/extract-cert] Error 1
Makefile:1120: recipe for target 'scripts' failed
make[5]: *** [scripts] Error 2
make[5]: Leaving directory '/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119'
Makefile:25: recipe for target '/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/.modules' failed
make[4]: *** [/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/.modules] Error 2
make[4]: Leaving directory '/home/lazy/openwrt-stm32mp1/target/linux/stm32mp1'
Makefile:11: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/lazy/openwrt-stm32mp1/target/linux'
time: target/linux/compile#0.64#0.22#0.84
    ERROR: target/linux failed to build.
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 1
make[2]: Leaving directory '/home/lazy/openwrt-stm32mp1'
target/Makefile:18: recipe for target '/home/lazy/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_compile' failed
make[1]: *** [/home/lazy/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/lazy/openwrt-stm32mp1'
/home/lazy/openwrt-stm32mp1/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by namezis** [comment]
In your configuration this error happens because the kernel is attepting to compile **extract-cert** tool.

The makefile for this is located in [kernel]/scripts/Makefile

[...]
hostprogs-$(CONFIG_MODULE_SIG_FORMAT) += sign-file
hostprogs-$(CONFIG_SYSTEM_TRUSTED_KEYRING) += extract-cert
hostprogs-$(CONFIG_SYSTEM_EXTRA_CERTIFICATE) += insert-sys-cert
[...]

The host enviroment is not correctly configured to complete this build.

However, it is not my configuration you are using! My configuration was based on kernel 5.4.56 you are using the configuration from OpenWRT (linux-5.4.119). Unfortunately, the kernel source must be specific to the baseboard and MCU otherwise it will not boot.

Please perform $ **make distclean** and then $ **git pull** and $ **./fixup.sh** 

Let see how it goes...

**Comment by LazyCat-xiao** [comment]
now i use your repo and configuration，sorry，i try to build, but it report this, i make distclean and try

**Comment by namezis** [comment]
No worries. I wonder how it goes...

Keep eye on the **TF-A** and **U-boot**, as they are executed before the kernel and must be correctly build for your system.

**Comment by LazyCat-xiao** [comment]
i try to load config-stm32mp1_dk2 and build. i port 5.10 to openwrt and it work but wifi worry

**Comment by namezis** [comment]
On STM32MP157C-DK2 Wi‑Fi® 802.11b/g/n + Bluetooth® Low Energy 4.1 ([User manual for STM32MP157 MPUs - UM2534](https://www.st.com/resource/en/user_manual/dm00591354-discovery-kits-with-stm32mp157-mpus-stmicroelectronics.pdf)) are provided by LBEE5KL1DX-883 ([muRata link](https://wireless.murata.com/pub/RFM/data/type1dx.pdf)).

From UM2534 document: [...] This module is driven by a SDIO for the Wi‑Fi® interface, and a USART for the Bluetooth® [...]

I made sure the Bluetooth is operational by providing gobbledegook sample.

WiFi should work too - but it requires some additional configuration.

**Comment by LazyCat-xiao** [comment]
thank you

**Comment by LazyCat-xiao** [comment]
i use your repo and build it success but i find wifi not work

**Comment by namezis** [comment]
Can you confirm the BLE is operational?

$ **ggk-start**

There will be some text scrolling. Then use your phone app e.g. "nRF Connect" to see if the device is broadcasting...

This will mean the LBEE5KL1DX-883 firmware is operational. The rest should be just adventure :-)

**Comment by namezis** [comment]
To make Wi-Fi operational we have to load another firmware Broadcom 4343.

**Comment by namezis** [comment]
FYI the calibration data is located [here](https://github.com/murata-wireless/cyw-fmac-nvram), and firmware [here](https://github.com/murata-wireless/cyw-fmac-fw). Bluetooth firmware is located [here](https://github.com/murata-wireless/cyw-bt-patch).

I will make appropriate package for it.

:-)

**Comment by LazyCat-xiao** [comment]
ble is probe but i cant see wlan probe in kermel log.  i try other way in tomorro。

**Comment by namezis** [comment]
Now the driver is loading up: 

brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Feb 16 2020 22:39:24 version 7.45.98.97 (r724416 CY) FWID 01-bf41ed64

Cheers.

**Comment by LazyCat-xiao** [comment]
now i git pull and build. but logs:
[    8.744203] Backport generated by backports.git v5.10.34-1-0-g7b5533e1
[    8.755631] Bluetooth: HCI UART driver ver 2.3
[    8.758619] Bluetooth: HCI UART protocol H4 registered
[    8.764886] Bluetooth: HCI UART protocol Broadcom registered
[    9.018825] Bluetooth: RFCOMM TTY layer initialized
[    9.022281] Bluetooth: RFCOMM socket layer initialized
[    9.027550] Bluetooth: RFCOMM ver 1.11
[    9.038729] xt_time: kernel timezone is -0000
[    9.133038] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    9.144153] Bluetooth: hci0: BCM: chip id 94
[    9.147927] Bluetooth: hci0: BCM: features 0x2e
[    9.156460] Bluetooth: hci0: BCM43430A1
[    9.158887] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[    9.177336] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.st,stm32mp157c-dk2.txt failed with error -2
[    9.187470] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.txt failed with error -2
[    9.804441] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0395
[   14.164518] usbcore: registered new interface driver brcmfmac
[   14.170570] kmodloader: done loading kernel modules from /etc/modules.d/*
[   15.174252] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50



wifi not work  😂😂😂(～￣▽￣)～，your kernel not patch openwrt's patches?

**Comment by LazyCat-xiao** [comment]
and i copy st 5.10 wifi firmware, it is work

**Comment by namezis** [comment]
That is because pull and build is not enough.

The correct procedure would be:

$ **rm .config && git pull && ./fixup.sh && make -j8**

Full cleanup is not required.

**Comment by LazyCat-xiao** [comment]
your kernel is st 5.4 and patch openwrt's patch?  or only st 5.4

**Comment by namezis** [comment]
Here you go:

![Selection_530](https://user-images.githubusercontent.com/1754783/118780643-9a377980-b8cf-11eb-96bd-bc4cd0873017.png)

For this I added luci, and changed device IP to static as above.

**Comment by namezis** [comment]
I did not use OpenWRT patches. I would use them only if I see issues.

Which patch in particular are you interested in?

**Comment by namezis** [comment]
Here is the system overview:

![Selection_531](https://user-images.githubusercontent.com/1754783/118781866-da4b2c00-b8d0-11eb-9364-b9fd1b100e18.png)

**Comment by namezis** [comment]
Kernel 5.10 I will test later.

I want to first make MYiR MYC-YA157C-V2 to work. There is a bit of work to get the booting done.

**Comment by LazyCat-xiao** [comment]
i was using try st 5.4 and build error. so i want to know what you do. 
i can entry luci and open wifi.

**Comment by namezis** [comment]
If you have build error paste it here please. Let see.

**Comment by LazyCat-xiao** [comment]
error is patch openwrt's patches. "use extend kernel tree" and "use git repo " have some diff?😢🤔

**Comment by LazyCat-xiao** [comment]
this i use "use extend kernel tree" logs

make[1]: Entering directory '/home/lazy/openwrt-stm32mp1'
make[2]: Entering directory '/home/lazy/openwrt-stm32mp1'
make[3]: Entering directory '/home/lazy/openwrt-stm32mp1/target/linux'
make[4]: Entering directory '/home/lazy/openwrt-stm32mp1/target/linux/stm32mp1'
rm -rf /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1
mkdir -p /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1
mkdir -p /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1
if [ -d /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119 ]; then rmdir /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119; fi
ln -s "/home/lazy/linux" /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119
export MAKEFLAGS= ; [ -d /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/user_headers ] && rm -rf /home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/user_headers
Makefile:25: recipe for target '/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/.prepared_8025fb9fa9a7aed789666a8b2417e5aa' failed
make[4]: *** [/home/lazy/openwrt-stm32mp1/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-stm32mp1/linux-5.4.119/.prepared_8025fb9fa9a7aed789666a8b2417e5aa] Error 1
make[4]: Leaving directory '/home/lazy/openwrt-stm32mp1/target/linux/stm32mp1'
Makefile:11: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/lazy/openwrt-stm32mp1/target/linux'
time: target/linux/compile#0.03#0.02#0.05
    ERROR: target/linux failed to build.
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 1
make[2]: Leaving directory '/home/lazy/openwrt-stm32mp1'
target/Makefile:18: recipe for target '/home/lazy/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_compile' failed
make[1]: *** [/home/lazy/openwrt-stm32mp1/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/lazy/openwrt-stm32mp1'
/home/lazy/openwrt-stm32mp1/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by namezis** [comment]
There is no details why the target prepared failed.

Depending on your configuration, it can possibly be one of these:

```
[...]
ifeq ($(strip $(CONFIG_EXTERNAL_KERNEL_TREE)),"")
  ifeq ($(strip $(CONFIG_KERNEL_GIT_CLONE_URI)),"")
    define Kernel/Prepare/Default
	$(LINUX_CAT) $(DL_DIR)/$(LINUX_SOURCE) | $(TAR) -C $(KERNEL_BUILD_DIR) $(TAR_OPTIONS)
	$(Kernel/Patch)
	$(if $(QUILT),touch $(LINUX_DIR)/.quilt_used)
    endef
  else
    define Kernel/Prepare/Default
	$(LINUX_CAT) $(DL_DIR)/$(LINUX_SOURCE) | $(TAR) -C $(KERNEL_BUILD_DIR) $(TAR_OPTIONS)
    endef
  endif
else
  define Kernel/Prepare/Default
	mkdir -p $(KERNEL_BUILD_DIR)
	if [ -d $(LINUX_DIR) ]; then \
		rmdir $(LINUX_DIR); \
	fi
	ln -s $(CONFIG_EXTERNAL_KERNEL_TREE) $(LINUX_DIR)
	$(_SINGLE) [ -d $(LINUX_DIR)/user_headers ] && rm -rf $(LINUX_DIR)/user_headers
  endef
endif
[...]
```
Most likely the first case.

**Comment by LazyCat-xiao** [comment]
i see it but i git your kernel repo in my disk. and i configure openwrt use external kernel tree use it, make and openwrt report same errors. config use git repo is ok, so i have some problem.

**Comment by namezis** [comment]
You can try to trace the make process a bit:

$ **make --debug -j1 V=s**

or

$ **remake --debug -j1 V=s** 


You can add --trace look into the man.

**Comment by namezis** [comment]
If you use external kernel tree, the last case is executed.

**Comment by LazyCat-xiao** [comment]
ok i try

**Comment by namezis** [comment]
I opted to **not** provide CONFIG_EXTERNAL_KERNEL_TREE (=""), and provide CONFIG_KERNEL_GIT_CLONE_URI.

I used the download (git clone) capability provided which I consider very simple to use and configure.

**Comment by LazyCat-xiao** [comment]
yes,use git is simple ,but i only try to use CONFIG_EXTERNAL_KERNEL_TREE. thank you tell me use --debug and it will report more logs.

**Comment by LazyCat-xiao** [comment]
i find compile kernel-headers failed and i dont know why for it 

<pre>GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
make[3]: Entering directory &apos;/home/lazy/openwrt-stm32mp1/toolchain/kernel-headers&apos;
Updating goal targets....
 File &apos;compile&apos; does not exist.
   File &apos;.compile&apos; does not exist.
     File &apos;.host-compile&apos; does not exist.
       File &apos;/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.built&apos; does not exist.
         File &apos;/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.configured&apos; does not exist.
           File &apos;/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.prepared&apos; does not exist.
          Must remake target &apos;/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.prepared&apos;.
rm -rf /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-*
mkdir -p /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi
if [ -d /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119 ]; then rmdir /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119; fi
ln -s &quot;/home/lazy/linux-stm32mp&quot; /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119
export MAKEFLAGS= ; [ -d /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/user_headers ] &amp;&amp; rm -rf /home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/user_headers
Makefile:115: recipe for target &apos;/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.prepared&apos; failed
make[3]: *** [/home/lazy/openwrt-stm32mp1/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/linux-5.4.119/.prepared] Error 1
make[3]: Leaving directory &apos;/home/lazy/openwrt-stm32mp1/toolchain/kernel-headers&apos;
time: toolchain/kernel-headers/compile#0.01#0.00#0.03
    ERROR: toolchain/kernel-headers failed to build.
toolchain/Makefile:95: recipe for target &apos;toolchain/kernel-headers/compile&apos; failed
make[2]: *** [toolchain/kernel-headers/compile] Error 1
make[2]: Leaving directory &apos;/home/lazy/openwrt-stm32mp1&apos;
toolchain/Makefile:93: recipe for target &apos;/home/lazy/openwrt-stm32mp1/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/stamp/.toolchain_compile&apos; failed
make[1]: *** [/home/lazy/openwrt-stm32mp1/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory &apos;/home/lazy/openwrt-stm32mp1&apos;
/home/lazy/openwrt-stm32mp1/include/toplevel.mk:228: recipe for target &apos;world&apos; failed
make: *** [world] Error 2
</pre>

**Comment by namezis** [comment]
As far as I can see make does not go beyond:

from: /home/lazy/openwrt-stm32mp1/toolchain/kernel-headers/Makefile
```
$(_SINGLE) [ -d $(LINUX_DIR)/user_headers ] && rm -rf $(LINUX_DIR)/user_headers
```
![image](https://user-images.githubusercontent.com/1754783/119128126-9430cc80-ba78-11eb-91f6-84e2545ccab1.png)

There should be the rest of the define:
```
rm -f $(BUILD_DIR_TOOLCHAIN)/linux
ln -s linux-$(LINUX_VERSION) $(BUILD_DIR_TOOLCHAIN)/linux
$(SED) 's/@expr length/@-expr length/' $(HOST_BUILD_DIR)/Makefile
```

which I cannot see. Something is wrong with the directory structure.?

**Comment by LazyCat-xiao** [comment]
i give up use "CONFIG_EXTERNAL_KERNEL_TREE". 😂 i try feedback it to openwrt. wait for answer. thank your help. thanks!

**Comment by namezis** [comment]
Do not give up...

I did have a look at your configuration, and I conclude that indeed there is OpenWRT source problem with it.

The highlighted line above in include/kernel-defaults.mk:
```
 $(_SINGLE) [ -d $(LINUX_DIR)/user_headers ] && rm -rf $(LINUX_DIR)/user_headers
```
is failing, because the directory $(LINUX_DIR)/user_headers does not exist. It passes the return code of 1 to make, and make terminates the build process as this target fails.

This has been committed by [Delete external source tree user_headers](https://git.openwrt.org/?p=openwrt/openwrt.git;a=patch;h=09760cbb3b9d79472c1c6803a32128b7fbb161c4). The line was introduced just recently Sep 2020.

There are 3 solutions:

1) As you mention "feedback it to openwrt", and wait until they find out what is going on.

2) Modify the introduced line to shield it returning the error to make.

Read [5.5 Errors in Recipes](https://www.gnu.org/software/make/manual/make.html#Errors-in-Recipes) which bascally means to prefix the line with -:
```
 -$(_SINGLE) [ -d $(LINUX_DIR)/user_headers ] && rm -rf $(LINUX_DIR)/user_headers
```

3) Remove the line from include/kernel-defaults.mk before using the OpenWRT build definition.

Hopefully this makes your day brighter :-)

**Comment by LazyCat-xiao** [comment]
i try delete it and try to build. hope it success!

**Comment by LazyCat-xiao** [comment]
i delete it and i build success. ヾ(≧▽≦*)o  but i afraid this will be make some bugs.   ||ヽ(*￣▽￣*)ノミ|Ю

**Comment by LazyCat-xiao** [comment]
sorry, i have a problem. i use your kernel repo and built it success. but i use st repo, it will report " HOSTCC  scripts/extract-cert  undefined referrnce to 'pthread_once'". st repo is https://github.com/STMicroelectronics/linux/tree/v5.4-stm32mp  , so  i have some puzzles. இ௰இ

**Comment by namezis** [comment]
Your error: scripts/extract-cert undefined reference to 'pthread_once' is related to the update done to the kernel to allow self-configuration using pkgconfig. You can read more about this on kernel forums.

Sorry but I only tested and support the kernel I selected in the config-stm32mp1_dk2.

I am closing this now. If you have a possible kernel update recipe, please create a pull request.
